In [ ]:
"""
FT-Transformer, bir Excel tablosundaki birbirinden farklı verileri (yaş, maaş, şehir gibi) alıp hepsini kendi anlayabileceği standart "bilgi paketlerine" dönüştürerek
işe başlar. Daha sonra, elindeki bu bilgilerin tamamına aynı anda bakıp aralarındaki ilişkileri ve birbirlerini nasıl etkilediklerini inceleyerek büyük resmi görür ve
sonuca ulaşır.
"""

'\nFT-Transformer, bir Excel tablosundaki birbirinden farklı verileri (yaş, maaş, şehir gibi) alıp hepsini kendi anlayabileceği standart "bilgi paketlerine" dönüştürerek \nişe başlar. Daha sonra, elindeki bu bilgilerin tamamına aynı anda bakıp aralarındaki ilişkileri ve birbirlerini nasıl etkilediklerini inceleyerek büyük resmi görür ve \nsonuca ulaşır.\n'

In [1]:
!pip install pytorch-tabular torch pandas scikit-learn

Collecting pytorch-tabular
  Downloading pytorch_tabular-1.2.0-py3-none-any.whl.metadata (21 kB)
Requirement already satisfied: torch in /usr/local/lib/python3.12/dist-packages (2.10.0+cu128)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.12/dist-packages (1.6.1)
Requirement already satisfied: numpy<=3.0.0 in /usr/local/lib/python3.12/dist-packages (from pytorch-tabular) (2.0.2)
Collecting pytorch-lightning<2.7.0,>=2.0.0 (from pytorch-tabular)
  Downloading pytorch_lightning-2.6.1-py3-none-any.whl.metadata (21 kB)
Requirement already satisfied: scipy<2.0,>=1.8 in /usr/local/lib/python3.12/dist-packages (from pytorch-tabular) (1.16.3)
Requirement already satisfied: omegaconf>=2.3.0 in /usr/local/lib/python3.12/dist-packages (from pytorch-tabular) (2.3.0)
Collecting torchmetrics<1.9.0,>=0.10.0 (from pytorch-tabular)
  Downloading torchmetrics-1.8.2-py3-none-any.whl.metadata (22 kB)
Requirement already satisfied: einops<0.9.0,>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pytorch-tabular) (0.8.2)
Requirement already satisfied: rich>=11.0.0 in /usr/local/lib/python3.12/dist-packages (from pytorch-tabular) (13.9.4)
Collecting scikit-base (from pytorch-tabular)
  Downloading scikit_base-0.13.1-py3-none-any.whl.metadata (8.8 kB)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from torch) (3.25.2)
Requirement already satisfied: typing-extensions>=4.10.0 in /usr/local/lib/python3.12/dist-packages (from torch) (4.15.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from torch) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch) (3.1.6)
Requirement already satisfied: fsspec>=0.8.5 in /usr/local/lib/python3.12/dist-packages (from torch) (2025.3.0)
Requirement already satisfied: cuda-bindings==12.9.4 in /usr/local/lib/python3.12/dist-packages (from torch) (12.9.4)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.8.93 in /usr/local/lib/python3.12/dist-packages (from torch) (12.8.93)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch) (12.8.90)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch) (12.8.90)
Requirement already satisfied: nvidia-cudnn-cu12==9.10.2.21 in /usr/local/lib/python3.12/dist-packages (from torch) (9.10.2.21)
Requirement already satisfied: nvidia-cublas-cu12==12.8.4.1 in /usr/local/lib/python3.12/dist-packages (from torch) (12.8.4.1)
Requirement already satisfied: nvidia-cufft-cu12==11.3.3.83 in /usr/local/lib/python3.12/dist-packages (from torch) (11.3.3.83)
Requirement already satisfied: nvidia-curand-cu12==10.3.9.90 in /usr/local/lib/python3.12/dist-packages (from torch) (10.3.9.90)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.3.90 in /usr/local/lib/python3.12/dist-packages (from torch) (11.7.3.90)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.8.93 in /usr/local/lib/python3.12/dist-packages (from torch) (12.5.8.93)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /usr/local/lib/python3.12/dist-packages (from torch) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.27.5 in /usr/local/lib/python3.12/dist-packages (from torch) (2.27.5)
Requirement already satisfied: nvidia-nvshmem-cu12==3.4.5 in /usr/local/lib/python3.12/dist-packages (from torch) (3.4.5)
Requirement already satisfied: nvidia-nvtx-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch) (12.8.90)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.8.93 in /usr/local/lib/python3.12/dist-packages (from torch) (12.8.93)
Requirement already satisfied: nvidia-cufile-cu12==1.13.1.3 in /usr/local/lib/python3.12/dist-packages (from torch) (1.13.1.3)
Requirement already satisfied: triton==3.6.0 in /usr/local/lib/python3.12/dist-packages (from torch) (3.6.0)
Requirement already satisfied: cuda-pathfinder~=1.1 in /usr/local/lib/python3.12/dist-packages (from cuda-bindings==12.9.4->torch) (1.5.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.3)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (3.6.0)
Requirement already satisfied: antlr4-python3-runtime==4.9.* in /usr/local/lib/python3.12/dist-packages (from omegaconf>=2.3.0->pytorch-tabular) (4.9.3)
Requirement already satisfied: PyYAML>=5.1.0 in /usr/local/lib/python3.12/dist-packages (from omegaconf>=2.3.0->pytorch-tabular) (6.0.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: tqdm>=4.57.0 in /usr/local/lib/python3.12/dist-packages (from pytorch-lightning<2.7.0,>=2.0.0->pytorch-tabular) (4.67.3)
Requirement already satisfied: packaging>=23.0 in /usr/local/lib/python3.12/dist-packages (from pytorch-lightning<2.7.0,>=2.0.0->pytorch-tabular) (26.0)
Collecting lightning-utilities>=0.10.0 (from pytorch-lightning<2.7.0,>=2.0.0->pytorch-tabular)
  Downloading lightning_utilities-0.15.3-py3-none-any.whl.metadata (5.5 kB)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=11.0.0->pytorch-tabular) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=11.0.0->pytorch-tabular) (2.20.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch) (3.0.3)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]>=2022.5.0->pytorch-lightning<2.7.0,>=2.0.0->pytorch-tabular) (3.13.4)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=11.0.0->pytorch-tabular) (0.1.2)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2022.5.0->pytorch-lightning<2.7.0,>=2.0.0->pytorch-tabular) (2.6.1)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2022.5.0->pytorch-lightning<2.7.0,>=2.0.0->pytorch-tabular) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2022.5.0->pytorch-lightning<2.7.0,>=2.0.0->pytorch-tabular) (26.1.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2022.5.0->pytorch-lightning<2.7.0,>=2.0.0->pytorch-tabular) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2022.5.0->pytorch-lightning<2.7.0,>=2.0.0->pytorch-tabular) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2022.5.0->pytorch-lightning<2.7.0,>=2.0.0->pytorch-tabular) (0.4.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2022.5.0->pytorch-lightning<2.7.0,>=2.0.0->pytorch-tabular) (1.23.0)
Requirement already satisfied: idna>=2.0 in /usr/local/lib/python3.12/dist-packages (from yarl<2.0,>=1.17.0->aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2022.5.0->pytorch-lightning<2.7.0,>=2.0.0->pytorch-tabular) (3.11)
Downloading pytorch_tabular-1.2.0-py3-none-any.whl (165 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 165.8/165.8 kB 22.5 MB/s eta 0:00:00
Downloading pytorch_lightning-2.6.1-py3-none-any.whl (857 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 857.3/857.3 kB 69.2 MB/s eta 0:00:00
Downloading torchmetrics-1.8.2-py3-none-any.whl (983 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 983.2/983.2 kB 83.2 MB/s eta 0:00:00
Downloading scikit_base-0.13.1-py3-none-any.whl (159 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 159.8/159.8 kB 23.2 MB/s eta 0:00:00
Downloading lightning_utilities-0.15.3-py3-none-any.whl (31 kB)
Installing collected packages: scikit-base, lightning-utilities, torchmetrics, pytorch-lightning, pytorch-tabular
Successfully installed lightning-utilities-0.15.3 pytorch-lightning-2.6.1 pytorch-tabular-1.2.0 scikit-base-0.13.1 torchmetrics-1.8.2

In [2]:
import numpy as np
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

from pytorch_tabular import TabularModel
from pytorch_tabular.models.ft_transformer.config import FTTransformerConfig
from pytorch_tabular.config import DataConfig, TrainerConfig, OptimizerConfig, ExperimentConfig

In [5]:
#ham veriyi ekleriz
train_df = pd.read_csv("train.csv")
test_df = pd.read_csv("test.csv")

print(train_df.shape, test_df.shape)
train_df.head()

(1460, 81) (1459, 80)

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000

In [8]:
#hedef değişkeni ayırırız bu sayede regresyon hedefi netleşir.
target_col = "SalePrice"

In [9]:
#ıd sutununu ayırırız ama submisson için saklarız.

test_ids = test_df["Id"].copy()

train_df = train_df.drop(columns=["Id"])
test_df = test_df.drop(columns=["Id"])

In [11]:
#train ve test’i birleştirip temel feature enginerring yaparız.(yaş,banyo,verenda vb.)
#birleşik veri sayesinde (trainle testi birleştirme) tutarlı preprocessing(ön işleme) elde edilir.
"""
eğitim ve test verileri birleştirilerek tüm tablo üzerinde toplu bir işlem yapılmasına olanak sağlanıyor. Ardından, mevcut
sütunlar kullanılarak evin toplam yaşı veya toplam banyo sayısı gibi daha anlamlı ve kapsamlı yeni özellikler (feature engineering)
 oluşturuluyor.
"""
all_df = pd.concat([train_df.drop(columns=[target_col]), test_df], axis=0).reset_index(drop=True)

all_df["HouseAge"] = 2010 - all_df["YearBuilt"]
all_df["RemodAge"] = 2010 - all_df["YearRemodAdd"]
all_df["GarageAge"] = 2010 - all_df["GarageYrBlt"]

all_df["TotalSF"] = (
    all_df["TotalBsmtSF"].fillna(0)
    + all_df["1stFlrSF"].fillna(0)
    + all_df["2ndFlrSF"].fillna(0)
)

all_df["TotalBath"] = (
    all_df["FullBath"].fillna(0)
    + 0.5 * all_df["HalfBath"].fillna(0)
    + all_df["BsmtFullBath"].fillna(0)
    + 0.5 * all_df["BsmtHalfBath"].fillna(0)
)

all_df["TotalPorchSF"] = (
    all_df["OpenPorchSF"].fillna(0)
    + all_df["EnclosedPorch"].fillna(0)
    + all_df["3SsnPorch"].fillna(0)
    + all_df["ScreenPorch"].fillna(0)
)

In [12]:
#yok anlamına gelen kategorikleri none ile sayısalları median/0 ile doldururuz. Bu sayede eğitim sırasında null hatalarını engelleriz

none_cols = [
    "Alley", "PoolQC", "Fence", "MiscFeature", "FireplaceQu",
    "GarageType", "GarageFinish", "GarageQual", "GarageCond",
    "BsmtQual", "BsmtCond", "BsmtExposure", "BsmtFinType1", "BsmtFinType2",
    "MasVnrType"
]

for col in none_cols:
    if col in all_df.columns:
        all_df[col] = all_df[col].fillna("None")

numeric_cols_all = all_df.select_dtypes(include=["int64", "float64"]).columns
categorical_cols_all = all_df.select_dtypes(include=["object"]).columns

for col in numeric_cols_all:
    all_df[col] = all_df[col].fillna(all_df[col].median())

for col in categorical_cols_all:
    all_df[col] = all_df[col].fillna("None")

In [13]:
#Kalite/durum belirten satırları sıralı sayıya çeviririz bu sayede model sütünlardaki düzen ilişkisini daha iyi anlar.
#Hiyerarşik düzen sağlamayı daha iyi anlar model.
qual_map = {
    "None": 0,
    "Po": 1,
    "Fa": 2,
    "TA": 3,
    "Gd": 4,
    "Ex": 5
}

ordinal_cols = [
    "ExterQual", "ExterCond", "BsmtQual", "BsmtCond",
    "HeatingQC", "KitchenQual", "FireplaceQu",
    "GarageQual", "GarageCond", "PoolQC"
]

for col in ordinal_cols:
    if col in all_df.columns:
        all_df[col] = all_df[col].map(qual_map).fillna(0).astype(int)

In [14]:

# Feature engineering  sonrası tekrar train ve test olarak ayırırız bu sayede eğitim ve tahmin setleri netleşir
X_full = all_df.iloc[:len(train_df)].copy()
X_test = all_df.iloc[len(train_df):].copy()

y_full = np.log1p(train_df[target_col].copy())

train_ready = X_full.copy()
train_ready[target_col] = y_full

print(train_ready.shape, X_test.shape)

(1460, 86) (1459, 85)

In [15]:
#fttransformera hangi sütünün kategorisel hangisinin sayısal olduğunu veririz.
#bu sayede embedding ve sayısal girişler daha doğru işlenir
categorical_cols = train_ready.select_dtypes(include=["object"]).columns.tolist()
categorical_cols = [c for c in categorical_cols if c != target_col]

continuous_cols = [c for c in train_ready.columns if c not in categorical_cols + [target_col]]

print("Categorical:", len(categorical_cols))
print("Continuous :", len(continuous_cols))

Categorical: 33
Continuous : 52

In [16]:
"""
train ve validation bölmesini yaparız
eğitim ve doğrulama veri seti oluştururuz.
ft-transformerin performansını daha adil ölçeriz
"""
train_data, valid_data = train_test_split(
    train_ready,
    test_size=0.2,
    random_state=42
)

print(train_data.shape, valid_data.shape)

#modeli eğitmek için %80, performansını kontrol etmek için ise %20(test_sizee) oranında iki ayrı gruba ayırıyoruz

(1168, 86) (292, 86)

In [17]:
#Dataconfig oluşturma
# PyTorch Tabular’a hedef, kategorik ve sayısal sütunları tanımlarız bu sayede veri akışı daha doğru yapılır.
data_config = DataConfig(
    target=[target_col],
    continuous_cols=continuous_cols,
    categorical_cols=categorical_cols,
)

In [27]:
#TrainerConfig oluşturma
#Epoch, batch size ve erken durdurma gibi benzeri eğitim ayarlarını tanımlarız.
trainer_config = TrainerConfig(
    auto_lr_find=False,
    batch_size=32,
    max_epochs=150,
    accelerator="auto",
    early_stopping="valid_loss",
    early_stopping_patience=10,
    checkpoints="valid_loss",
    load_best=True
)

In [28]:
# Öğrenme oranı ve ağırlık çürümesi gibi optimizasyon ayarlarını tanımladık bu sayede eğitim daha stabil olur.
optimizer_config = OptimizerConfig(
    optimizer="AdamW",
    optimizer_params={"weight_decay": 1e-5},
    lr_scheduler="ReduceLROnPlateau",
    lr_scheduler_params={"patience": 3, "factor": 0.5},
)

In [29]:
# ExperimentConfig oluşturduk. Sonuçlar düzenli tutulur.
experiment_config = ExperimentConfig(
    project_name="ames_housing_ft_transformer",
    run_name="ft_transformer_regression_v1",
    exp_watch="gradients",
    log_target="tensorboard"
)

In [30]:
"""
FTTransformerConfig oluşturduk. FT-Transformer mimarisinin ana hiperparametrelerini belirledik
PyTorch Tabular tarafında görev türü regression olarak verilebiliyor ve regresyonda varsayılan olarak MSE takibi yapılıyor;
ayrıca TabularModel bu config’leri merkezden yönetebiliyor.
"""
model_config = FTTransformerConfig(
    task="regression",
    learning_rate=1e-4,
    input_embed_dim=32,
    num_heads=8,
    num_attn_blocks=4,
    attn_dropout=0.1,
    ff_dropout=0.1,
)

In [31]:
#Tüm config’leri bir araya getirip model nesnesini kurarız. Eğitim için pipeline hazır olur
tabular_model = TabularModel(
    data_config=data_config,
    model_config=model_config,
    optimizer_config=optimizer_config,
    trainer_config=trainer_config,
    experiment_config=experiment_config,
)

In [32]:
# FT-Transformer train ve validation verisiyle eğitilir.
#Tabular ilişkileri attention mekanizmasıyla öğrenir.
tabular_model.fit(
    train=train_data,
    validation=valid_data,
)

INFO:lightning_fabric.utilities.seed:Seed set to 42
2026-04-03 11:59:28,125 - {pytorch_tabular.tabular_model:547} - INFO - Preparing the DataLoaders
2026-04-03 11:59:28,139 - {pytorch_tabular.tabular_datamodule:527} - INFO - Setting up the datamodule for regression task
/usr/local/lib/python3.12/dist-packages/pytorch_tabular/tabular_datamodule.py:388: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-0.8667643   0.07410996 -0.63154574 ... -0.8667643  -0.16110861
  1.48542135]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  data.loc[:, self.config.continuous_cols] = self.scaler.fit_transform(
/usr/local/lib/python3.12/dist-packages/pytorch_tabular/tabular_datamodule.py:388: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-0.21289571 -0.26524463 -0.17784146 ... -0.23409563 -0.28337613
 -0.65139925]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  data.loc[:, self.config.continuous_cols] = self.scaler.fit_transform(
/usr/local/lib/python3.12/dist-packages/pytorch_tabular/tabular_datamodule.py:388: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-0.82044456 -0.08893368 -0.82044456 ... -0.82044456  0.64257719
  0.64257719]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  data.loc[:, self.config.continuous_cols] = self.scaler.fit_transform(
/usr/local/lib/python3.12/dist-packages/pytorch_tabular/tabular_datamodule.py:388: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ 0.3722173   1.26860866  1.26860866 ...  1.26860866  2.16500001
 -0.52417405]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  data.loc[:, self.config.continuous_cols] = self.scaler.fit_transform(
/usr/local/lib/python3.12/dist-packages/pytorch_tabular/tabular_datamodule.py:388: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-0.45546896  0.71860895 -1.98829291 ... -0.52069551 -1.72738671
  1.17519481]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  data.loc[:, self.config.continuous_cols] = self.scaler.fit_transform(
/usr/local/lib/python3.12/dist-packages/pytorch_tabular/tabular_datamodule.py:388: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-1.34606303  0.43921379 -1.6838181  ...  0.24621089  0.63221669
  1.06647321]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  data.loc[:, self.config.continuous_cols] = self.scaler.fit_transform(
/usr/local/lib/python3.12/dist-packages/pytorch_tabular/tabular_datamodule.py:388: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-0.68742066  1.05424384 -0.68742066 ... -0.68742066  1.05424384
  1.05424384]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  data.loc[:, self.config.continuous_cols] = self.scaler.fit_transform(
/usr/local/lib/python3.12/dist-packages/pytorch_tabular/tabular_datamodule.py:388: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ 2.5209189  -0.24121363 -0.24121363 ... -0.24121363 -0.24121363
 -0.24121363]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  data.loc[:, self.config.continuous_cols] = self.scaler.fit_transform(
/usr/local/lib/python3.12/dist-packages/pytorch_tabular/tabular_datamodule.py:388: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-0.56620052  0.58592876 -1.7183298  ... -0.56620052 -0.56620052
  0.58592876]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  data.loc[:, self.config.continuous_cols] = self.scaler.fit_transform(
/usr/local/lib/python3.12/dist-packages/pytorch_tabular/tabular_datamodule.py:388: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[0.11014407 0.11014407 0.11014407 ... 0.11014407 0.11014407 0.11014407]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  data.loc[:, self.config.continuous_cols] = self.scaler.fit_transform(
/usr/local/lib/python3.12/dist-packages/pytorch_tabular/tabular_datamodule.py:388: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-1.16829211 -0.1321758  -0.1321758  ... -1.16829211 -0.1321758
  0.90394052]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  data.loc[:, self.config.continuous_cols] = self.scaler.fit_transform(
/usr/local/lib/python3.12/dist-packages/pytorch_tabular/tabular_datamodule.py:388: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ 0.37423523 -0.95820221 -0.96596398 ... -0.79003049 -0.66584215
  0.99776421]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  data.loc[:, self.config.continuous_cols] = self.scaler.fit_transform(
/usr/local/lib/python3.12/dist-packages/pytorch_tabular/tabular_datamodule.py:388: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-0.80192292  0.9550877  -0.80192292 ... -0.80192292  0.36790021
 -0.80192292]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  data.loc[:, self.config.continuous_cols] = self.scaler.fit_transform(
/usr/local/lib/python3.12/dist-packages/pytorch_tabular/tabular_datamodule.py:388: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-0.11899866 -0.11899866 -0.11899866 ... -0.11899866 -0.11899866
 -0.11899866]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  data.loc[:, self.config.continuous_cols] = self.scaler.fit_transform(
/usr/local/lib/python3.12/dist-packages/pytorch_tabular/tabular_datamodule.py:388: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-0.40709315  0.08317013 -1.39525026 ... -1.26553079 -0.19343756
  0.0526479 ]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  data.loc[:, self.config.continuous_cols] = self.scaler.fit_transform(
/usr/local/lib/python3.12/dist-packages/pytorch_tabular/tabular_datamodule.py:388: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-1.05556573  0.7736639  -1.05556573 ... -1.05556573 -1.05556573
  0.7736639 ]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  data.loc[:, self.config.continuous_cols] = self.scaler.fit_transform(
/usr/local/lib/python3.12/dist-packages/pytorch_tabular/tabular_datamodule.py:388: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-0.76409752  1.23694711 -0.76409752 ... -0.76409752  1.23694711
 -0.76409752]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  data.loc[:, self.config.continuous_cols] = self.scaler.fit_transform(
/usr/local/lib/python3.12/dist-packages/pytorch_tabular/tabular_datamodule.py:388: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ 0.13621832  0.13621832 -1.10677385 ... -1.10677385  0.13621832
 -1.10677385]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  data.loc[:, self.config.continuous_cols] = self.scaler.fit_transform(
/usr/local/lib/python3.12/dist-packages/pytorch_tabular/tabular_datamodule.py:388: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-0.21275711 -0.21275711 -0.21275711 ... -0.21275711 -0.21275711
 -0.21275711]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  data.loc[:, self.config.continuous_cols] = self.scaler.fit_transform(
/usr/local/lib/python3.12/dist-packages/pytorch_tabular/tabular_datamodule.py:388: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-0.76707624 -0.76707624 -0.76707624 ... -0.76707624  0.74634445
  0.74634445]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  data.loc[:, self.config.continuous_cols] = self.scaler.fit_transform(
/usr/local/lib/python3.12/dist-packages/pytorch_tabular/tabular_datamodule.py:388: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-0.96456591  0.27075534 -1.58222654 ... -0.96456591  0.27075534
  0.27075534]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  data.loc[:, self.config.continuous_cols] = self.scaler.fit_transform(
/usr/local/lib/python3.12/dist-packages/pytorch_tabular/tabular_datamodule.py:388: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-0.95859215  0.59214972 -0.95859215 ... -0.95859215  0.59214972
  0.59214972]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  data.loc[:, self.config.continuous_cols] = self.scaler.fit_transform(
/usr/local/lib/python3.12/dist-packages/pytorch_tabular/tabular_datamodule.py:388: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-1.0162412   0.63922564 -1.0162412  ... -1.0162412   1.19104792
  0.63922564]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  data.loc[:, self.config.continuous_cols] = self.scaler.fit_transform(
/usr/local/lib/python3.12/dist-packages/pytorch_tabular/tabular_datamodule.py:388: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ 0.25314289  0.25314289 -3.91123593 ...  0.25314289  0.25314289
  0.25314289]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  data.loc[:, self.config.continuous_cols] = self.scaler.fit_transform(
/usr/local/lib/python3.12/dist-packages/pytorch_tabular/tabular_datamodule.py:388: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ 0.2580102   0.2580102  -3.92748859 ...  0.2580102   0.2580102
  0.2580102 ]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  data.loc[:, self.config.continuous_cols] = self.scaler.fit_transform(
/usr/local/lib/python3.12/dist-packages/pytorch_tabular/tabular_datamodule.py:388: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ 1.18840233 -0.74015748  1.79011299 ... -0.74015748 -0.74015748
  0.36297873]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  data.loc[:, self.config.continuous_cols] = self.scaler.fit_transform(
/usr/local/lib/python3.12/dist-packages/pytorch_tabular/tabular_datamodule.py:388: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-0.71435182 -0.13801492 -0.71435182 ... -0.71435182  2.74366957
 -0.42618337]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  data.loc[:, self.config.continuous_cols] = self.scaler.fit_transform(
/usr/local/lib/python3.12/dist-packages/pytorch_tabular/tabular_datamodule.py:388: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-0.35192107 -0.35192107  2.29082573 ... -0.35192107 -0.35192107
 -0.35192107]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  data.loc[:, self.config.continuous_cols] = self.scaler.fit_transform(
/usr/local/lib/python3.12/dist-packages/pytorch_tabular/tabular_datamodule.py:388: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-0.12100805 -0.12100805 -0.12100805 ... -0.12100805 -0.12100805
 -0.12100805]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  data.loc[:, self.config.continuous_cols] = self.scaler.fit_transform(
/usr/local/lib/python3.12/dist-packages/pytorch_tabular/tabular_datamodule.py:388: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-0.27583782 -0.27583782 -0.27583782 ... -0.27583782 -0.27583782
 -0.27583782]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  data.loc[:, self.config.continuous_cols] = self.scaler.fit_transform(
/usr/local/lib/python3.12/dist-packages/pytorch_tabular/tabular_datamodule.py:388: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-0.07099284 -0.07099284 -0.07099284 ... -0.07099284 -0.07099284
 -0.07099284]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  data.loc[:, self.config.continuous_cols] = self.scaler.fit_transform(
/usr/local/lib/python3.12/dist-packages/pytorch_tabular/tabular_datamodule.py:388: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-0.06801146 -0.06801146 -0.06801146 ... -0.06801146 -0.06801146
 -0.06801146]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  data.loc[:, self.config.continuous_cols] = self.scaler.fit_transform(
/usr/local/lib/python3.12/dist-packages/pytorch_tabular/tabular_datamodule.py:388: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-0.09274033 -0.09274033 -0.09274033 ... -0.09274033 -0.09274033
 -0.09274033]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  data.loc[:, self.config.continuous_cols] = self.scaler.fit_transform(
/usr/local/lib/python3.12/dist-packages/pytorch_tabular/tabular_datamodule.py:388: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-0.13341669 -0.5080097  -0.5080097  ... -0.88260272 -0.13341669
 -0.13341669]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  data.loc[:, self.config.continuous_cols] = self.scaler.fit_transform(
/usr/local/lib/python3.12/dist-packages/pytorch_tabular/tabular_datamodule.py:388: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ 1.65006527  0.89367742  0.13728958 ... -1.37548612 -0.61909827
  0.89367742]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  data.loc[:, self.config.continuous_cols] = self.scaler.fit_transform(
/usr/local/lib/python3.12/dist-packages/pytorch_tabular/tabular_datamodule.py:388: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ 0.45546896 -0.71860895  1.98829291 ...  0.52069551  1.72738671
 -1.17519481]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  data.loc[:, self.config.continuous_cols] = self.scaler.fit_transform(
/usr/local/lib/python3.12/dist-packages/pytorch_tabular/tabular_datamodule.py:388: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ 1.34606303 -0.43921379  1.6838181  ... -0.24621089 -0.63221669
 -1.06647321]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  data.loc[:, self.config.continuous_cols] = self.scaler.fit_transform(
/usr/local/lib/python3.12/dist-packages/pytorch_tabular/tabular_datamodule.py:388: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-0.83842468 -0.46841381  0.6786199  ... -0.83842468  1.38164056
 -0.65341924]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  data.loc[:, self.config.continuous_cols] = self.scaler.fit_transform(
/usr/local/lib/python3.12/dist-packages/pytorch_tabular/tabular_datamodule.py:392: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-0.8667643   0.07410996 -0.63154574 -0.16110861 -0.8667643   2.89673275
 -0.16110861  2.42629562  2.89673275 -0.16110861 -0.16110861 -0.8667643
 -0.63154574 -0.8667643   0.07410996 -0.8667643   0.07410996 -0.8667643
 -0.63154574 -0.8667643  -0.8667643   0.07410996  0.07410996 -0.8667643
 -0.8667643   1.48542135 -0.8667643  -0.8667643   0.07410996  1.48542135
 -0.16110861  0.07410996 -0.16110861 -0.8667643  -0.8667643  -0.8667643
 -0.16110861  0.07410996  0.07410996 -0.8667643  -0.16110861  0.07410996
 -0.8667643  -0.8667643  -0.8667643   0.30932853 -0.8667643  -0.8667643
  0.07410996 -0.16110861 -0.8667643  -0.8667643   2.42629562 -0.8667643
  1.48542135 -0.8667643   0.07410996 -0.8667643   0.54454709 -0.8667643
 -0.63154574 -0.8667643   0.07410996 -0.8667643  -0.8667643  -0.8667643
 -0.16110861  0.07410996 -0.8667643   2.42629562  0.77976566 -0.8667643
 -0.8667643   0.77976566 -0.8667643   1.48542135  0.07410996  0.07410996
 -0.8667643  -0.8667643   2.42629562 -0.63154574 -0.8667643  -0.63154574
  0.07410996 -0.16110861  0.07410996  1.48542135  1.48542135  0.07410996
 -0.63154574  0.07410996 -0.8667643   0.07410996  0.77976566 -0.8667643
 -0.16110861  2.42629562 -0.8667643   0.07410996 -0.8667643   0.07410996
 -0.8667643  -0.27871789  0.54454709 -0.8667643  -0.8667643   1.48542135
 -0.8667643   0.07410996 -0.63154574 -0.8667643  -0.8667643   0.30932853
  0.07410996 -0.63154574 -0.8667643  -0.8667643   0.77976566 -0.8667643
  1.48542135  1.48542135  0.07410996 -0.16110861 -0.8667643  -0.8667643
  0.07410996 -0.39632717 -0.8667643   0.07410996  0.07410996 -0.8667643
  0.07410996  0.42693781 -0.8667643  -0.8667643   1.48542135 -0.8667643
 -0.8667643   0.07410996  0.07410996 -0.8667643   0.07410996 -0.16110861
  3.13195132  0.66215637 -0.16110861 -0.8667643   0.66215637 -0.63154574
 -0.63154574  0.07410996 -0.8667643   0.77976566 -0.63154574  0.77976566
  0.77976566 -0.8667643  -0.63154574 -0.8667643  -0.8667643   0.77976566
 -0.8667643  -0.8667643  -0.16110861  0.77976566  0.07410996  0.07410996
  0.07410996  0.30932853 -0.8667643  -0.27871789 -0.16110861  2.42629562
 -0.16110861 -0.16110861 -0.16110861 -0.16110861 -0.16110861  2.42629562
  0.54454709 -0.8667643   0.54454709  0.07410996  0.07410996  0.30932853
 -0.8667643   1.48542135  1.48542135  2.42629562  2.42629562 -0.63154574
 -0.16110861  0.54454709  1.48542135 -0.8667643   1.48542135  0.30932853
  2.42629562 -0.16110861 -0.8667643   0.07410996  0.30932853  0.07410996
 -0.8667643   0.54454709  0.07410996 -0.8667643  -0.16110861 -0.8667643
  0.07410996 -0.8667643  -0.8667643   2.42629562 -0.8667643  -0.8667643
  1.48542135  0.54454709  0.54454709  0.77976566 -0.8667643   1.48542135
 -0.8667643  -0.16110861 -0.8667643  -0.8667643  -0.16110861 -0.63154574

┏━━━┳━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━┳━━━━━━━┳━━━━━━━┓
┃   ┃ Name             ┃ Type                  ┃ Params ┃ Mode  ┃ FLOPs ┃
┡━━━╇━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━╇━━━━━━━╇━━━━━━━┩
│ 0 │ _backbone        │ FTTransformerBackbone │  181 K │ train │     0 │
│ 1 │ _embedding_layer │ Embedding2dLayer      │ 12.7 K │ train │     0 │
│ 2 │ _head            │ LinearHead            │     33 │ train │     0 │
│ 3 │ loss             │ MSELoss               │      0 │ train │     0 │
└───┴──────────────────┴───────────────────────┴────────┴───────┴───────┘

Trainable params: 193 K
Non-trainable params: 0
Total params: 193 K
Total estimated model params size (MB): 0
Modules in train mode: 152
Modules in eval mode: 0
Total FLOPs: 0

Output()

/usr/local/lib/python3.12/dist-packages/pytorch_lightning/utilities/_pytree.py:21: `isinstance(treespec, LeafSpec)`
is deprecated, use `isinstance(treespec, TreeSpec) and treespec.is_leaf()` instead.

/usr/local/lib/python3.12/dist-packages/pytorch_lightning/trainer/connectors/data_connector.py:434: The
'val_dataloader' does not have many workers which may be a bottleneck. Consider increasing the value of the
`num_workers` argument` to `num_workers=11` in the `DataLoader` to improve performance.

/usr/local/lib/python3.12/dist-packages/pytorch_lightning/trainer/connectors/data_connector.py:434: The
'train_dataloader' does not have many workers which may be a bottleneck. Consider increasing the value of the
`num_workers` argument` to `num_workers=11` in the `DataLoader` to improve performance.

/usr/local/lib/python3.12/dist-packages/pytorch_lightning/loops/fit_loop.py:317: The number of training batches
(37) is smaller than the logging interval Trainer(log_every_n_steps=50). Set a lower value for log_every_n_steps if
you want to see logs for the training epoch.

2026-04-03 12:01:11,807 - {pytorch_tabular.tabular_model:690} - INFO - Training the model completed
2026-04-03 12:01:11,807 - {pytorch_tabular.tabular_model:1531} - INFO - Loading the best model

In [33]:
#Doğrulama verisi üzerinde tahmin üretiriz lineer regression ve catboost ile kıyasalamak için
pred_df = tabular_model.predict(valid_data)

pred_df.head()


#PyTorch Tabular sürümüne göre tahmin sütunu adı genelde prediction olur. Emin olmak için önce:

print(pred_df.columns)


#Sonra doğru sütunu al:

pred_col = "prediction" if "prediction" in pred_df.columns else pred_df.columns[-1]

y_true = valid_data[target_col].values
y_pred = pred_df[pred_col].values

/usr/local/lib/python3.12/dist-packages/pytorch_tabular/tabular_datamodule.py:392: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-0.8667643   0.07410996 -0.63154574 -0.16110861 -0.8667643   2.89673275
 -0.16110861  2.42629562  2.89673275 -0.16110861 -0.16110861 -0.8667643
 -0.63154574 -0.8667643   0.07410996 -0.8667643   0.07410996 -0.8667643
 -0.63154574 -0.8667643  -0.8667643   0.07410996  0.07410996 -0.8667643
 -0.8667643   1.48542135 -0.8667643  -0.8667643   0.07410996  1.48542135
 -0.16110861  0.07410996 -0.16110861 -0.8667643  -0.8667643  -0.8667643
 -0.16110861  0.07410996  0.07410996 -0.8667643  -0.16110861  0.07410996
 -0.8667643  -0.8667643  -0.8667643   0.30932853 -0.8667643  -0.8667643
  0.07410996 -0.16110861 -0.8667643  -0.8667643   2.42629562 -0.8667643
  1.48542135 -0.8667643   0.07410996 -0.8667643   0.54454709 -0.8667643
 -0.63154574 -0.8667643   0.07410996 -0.8667643  -0.8667643  -0.8667643
 -0.16110861  0.07410996 -0.8667643   2.42629562  0.77976566 -0.8667643
 -0.8667643   0.77976566 -0.8667643   1.48542135  0.07410996  0.07410996
 -0.8667643  -0.8667643   2.42629562 -0.63154574 -0.8667643  -0.63154574
  0.07410996 -0.16110861  0.07410996  1.48542135  1.48542135  0.07410996
 -0.63154574  0.07410996 -0.8667643   0.07410996  0.77976566 -0.8667643
 -0.16110861  2.42629562 -0.8667643   0.07410996 -0.8667643   0.07410996
 -0.8667643  -0.27871789  0.54454709 -0.8667643  -0.8667643   1.48542135
 -0.8667643   0.07410996 -0.63154574 -0.8667643  -0.8667643   0.30932853
  0.07410996 -0.63154574 -0.8667643  -0.8667643   0.77976566 -0.8667643
  1.48542135  1.48542135  0.07410996 -0.16110861 -0.8667643  -0.8667643
  0.07410996 -0.39632717 -0.8667643   0.07410996  0.07410996 -0.8667643
  0.07410996  0.42693781 -0.8667643  -0.8667643   1.48542135 -0.8667643
 -0.8667643   0.07410996  0.07410996 -0.8667643   0.07410996 -0.16110861
  3.13195132  0.66215637 -0.16110861 -0.8667643   0.66215637 -0.63154574
 -0.63154574  0.07410996 -0.8667643   0.77976566 -0.63154574  0.77976566
  0.77976566 -0.8667643  -0.63154574 -0.8667643  -0.8667643   0.77976566
 -0.8667643  -0.8667643  -0.16110861  0.77976566  0.07410996  0.07410996
  0.07410996  0.30932853 -0.8667643  -0.27871789 -0.16110861  2.42629562
 -0.16110861 -0.16110861 -0.16110861 -0.16110861 -0.16110861  2.42629562
  0.54454709 -0.8667643   0.54454709  0.07410996  0.07410996  0.30932853
 -0.8667643   1.48542135  1.48542135  2.42629562  2.42629562 -0.63154574
 -0.16110861  0.54454709  1.48542135 -0.8667643   1.48542135  0.30932853
  2.42629562 -0.16110861 -0.8667643   0.07410996  0.30932853  0.07410996
 -0.8667643   0.54454709  0.07410996 -0.8667643  -0.16110861 -0.8667643
  0.07410996 -0.8667643  -0.8667643   2.42629562 -0.8667643  -0.8667643
  1.48542135  0.54454709  0.54454709  0.77976566 -0.8667643   1.48542135
 -0.8667643  -0.16110861 -0.8667643  -0.8667643  -0.16110861 -0.63154574
  0.07410996 -0.16110861 -0.8667643   0.07410996 -0.8667643  -0.8667643
  0.07410996  0.30932853 -0.8667643   0.66215637  0.07410996  1.48542135
 -0.63154574  0.54454709  0.07410996  0.07410996  0.07410996  3.13195132
  0.54454709 -0.8667643   1.48542135 -0.8667643   0.07410996  0.54454709
 -0.16110861 -0.63154574 -0.8667643   1.48542135 -0.16110861  2.42629562
  0.07410996  0.07410996 -0.8667643  -0.8667643  -0.8667643   0.54454709
 -0.8667643   0.07410996  1.48542135  1.48542135 -0.8667643   0.54454709
 -0.8667643   1.48542135  0.07410996  2.42629562  0.77976566 -0.8667643
  2.42629562  1.48542135 -0.8667643  -0.16110861  0.07410996  2.89673275
  0.07410996 -0.63154574 -0.8667643  -0.8667643   0.07410996 -0.63154574
 -0.8667643   0.07410996  0.30932853 -0.8667643 ]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  data.loc[:, self.config.continuous_cols] = self.scaler.transform(data.loc[:, self.config.continuous_cols])
/usr/local/lib/python3.12/dist-packages/pytorch_tabular/tabular_datamodule.py:392: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-2.11593961e-01  1.45643229e-01 -1.60825740e-01 -5.29034817e-01
  2.05337731e-01 -8.55308971e-01  4.62154264e-01 -7.81946102e-01
 -8.13931941e-01  5.37097829e-01 -4.08901956e-01 -7.73278228e-02
  6.79732355e-01 -4.82244286e-02 -2.44230675e-01 -1.64266077e-01
 -2.27400916e-01 -3.43070636e-01 -2.25634257e-01 -2.29127613e-03
  2.26444666e-01 -1.57106456e-01 -1.91230883e-01 -4.48326362e-01
 -1.55525761e-01 -2.60130612e-01 -1.66497647e-01  7.85545973e-01
  1.38876076e-02 -6.00631026e-01 -3.02344481e-01 -6.01055973e-03
  6.82521817e-01 -2.05922053e-01  2.61405931e-01 -1.38510038e-01
 -3.24474218e-01 -2.31492128e-01  3.58107305e-01  1.87113241e-01
 -4.13737025e-01 -1.68264307e-01 -8.66260319e-02  1.87299206e-01
 -6.92383810e-02 -7.34225751e-02 -2.68684964e-01 -2.74077926e-01
  2.59267343e-01  6.08435631e-02 -3.24474218e-01 -8.09541244e-02
 -7.46147997e-01  4.47091165e-01 -5.81290751e-01  8.88311722e-02
 -1.27631134e-01  4.57598142e-01 -2.66918305e-01 -3.24474218e-01
 -4.05926529e-01 -2.96579591e-01 -1.02154041e-01  3.62384481e-01
  4.29238604e-01  1.79023800e-01 -5.16647660e-02  1.44527444e-01
  2.07888211e-03 -6.93613116e-01 -3.41396959e-01 -2.26843024e-01
 -1.94950167e-01 -1.99506289e-01  2.07290355e-01 -7.25505973e-01
 -1.15078551e-01 -1.37280732e-02 -2.55202561e-01 -3.24474218e-01
 -8.37735356e-01 -1.60174865e-01  1.02841519e+00 -4.56136858e-01
 -2.64593752e-01 -4.24894876e-01  3.56659555e-03 -5.03836670e-01
 -5.81569697e-01  3.84348793e-02 -2.40790337e-01  9.61043141e-03
 -2.20892170e-01 -2.87911718e-02  8.21570005e-03 -4.20876107e-02
 -3.18523365e-01 -6.46657161e-01 -1.58036277e-01  2.15286815e-01
  1.36252038e-01 -2.35397376e-01  2.75353245e-01 -4.24894876e-01
  5.08366363e-01 -2.12895710e-01 -2.56597293e-01 -3.83703810e-01
 -1.34325844e-01  8.52048707e-02 -4.24894876e-01 -2.10106248e-01
 -3.52647792e-01 -4.24894876e-01 -1.34325844e-01 -3.24474218e-01
 -4.36052726e-01 -2.22751812e-01 -1.63615202e-01 -3.22109703e-03
 -6.16623945e-01 -5.81290751e-01 -1.78213391e-01  2.19749955e-01
  7.13505392e-02  2.63730484e-01 -1.76167785e-01 -1.47808247e-01
 -1.08290859e-01 -5.11068734e-02 -2.20334277e-01  7.00487900e-02
 -2.69315300e-02 -4.80684130e-01 -1.57106456e-01  1.64239647e-01
 -1.78585319e-01 -1.38510038e-01 -2.38465785e-01  1.00842404e+00
  4.13617613e-01  2.42716531e-01 -1.37952146e-01 -2.12895710e-01
  2.22788416e+00 -2.65151645e-01  7.53487691e-02  5.20268070e-01
 -3.24474218e-01 -2.27028988e-01  8.46469781e-02 -2.88211203e-01
  2.04359365e+00  8.46469781e-02 -8.40225333e-02 -1.57106456e-01
  2.05523695e-01  5.76821720e-02 -1.47994211e-01 -6.41243660e-02
  3.34138465e-02 -3.45023260e-01 -1.08755769e-01 -1.97832612e-01
 -2.05457143e-01 -2.50088546e-01 -3.05970782e-01 -1.02432987e-01
  4.98975172e-01  1.24599328e+00  1.56987044e-01 -4.82543772e-01
 -4.36052726e-01 -8.12630191e-01 -1.08250896e-03  5.97908116e-01
 -1.81188817e-01  2.85302329e-01 -3.24474218e-01 -7.97102182e-01
 -1.24562725e-01 -1.83885298e-01  8.40166423e-03 -6.79851767e-01
  6.29821511e-02 -3.62297390e-02  2.39462158e-01 -6.17832713e-01
 -3.47254830e-01 -8.07888105e-01 -8.15419654e-01 -4.91841981e-01
 -1.01317202e-01 -7.52822169e-02 -4.93608640e-01 -2.68684964e-01
 -6.85616656e-01 -2.03597501e-01 -7.48007639e-01 -2.79749833e-01
  5.58556041e+00  1.03975901e+00  3.32761247e-05 -1.38510038e-01
 -2.08246606e-01 -8.73698886e-02 -8.01172855e-02 -1.74215161e-01
 -2.12895710e-01 -1.12753999e-01  2.58895415e-01 -2.31771075e-01
 -1.27352187e-01 -6.93613116e-01  2.64202638e+00 -1.57106456e-01
 -6.29269510e-01 -2.34932466e-01 -3.49579383e-01 -5.25016048e-02
  2.47365636e-01 -4.13737025e-01  2.13334191e-01 -4.62087712e-01
 -1.64080113e-01  1.59032650e-01 -2.96579591e-01  1.02613060e-02
 -1.45018784e-01 -1.83885298e-01  3.81559331e-02 -2.79377905e-01
 -3.12200582e-01  5.99767757e-01 -6.03121004e-02 -1.82211620e-01
 -3.65200374e-01 -1.50690692e-01  3.41649475e-01 -2.48972761e-01
 -2.01737859e-01  5.44277988e-02 -1.14985569e-01  2.78235690e-01
 -1.45948605e-01 -3.43070636e-01 -1.43159143e-01  2.90230379e-01
 -6.01188918e-01 -4.36052726e-01  1.04515197e+00  8.77359259e-03
 -1.43717035e-01 -4.91841981e-01  8.02768199e-02 -6.18018677e-01
 -6.26666011e-01 -8.37735356e-01 -3.28844377e-01 -6.41243660e-02
  3.28817947e-01  5.21032466e-02 -3.68600748e-03  1.96225486e-01
 -1.18425907e-01  3.63407284e-01 -5.75525862e-01 -5.81569697e-01
 -2.37701389e-02 -2.73334069e-01  2.97668947e-01 -4.92306891e-01
 -9.43435453e-02 -7.52935690e-01 -7.88155363e-02 -1.80351979e-01
 -7.59444436e-01 -2.66825322e-01  1.33944028e+00  2.23489778e-02
  3.08361887e-01 -8.51403723e-01 -2.38465785e-01 -1.55060850e-01
 -4.89477465e-03 -1.42601250e-01  1.60892292e-01 -4.43026383e-01
  5.08459345e-01 -2.31585110e-01 -1.49295961e-01 -2.38930695e-01]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  data.loc[:, self.config.continuous_cols] = self.scaler.transform(data.loc[:, self.config.continuous_cols])
/usr/local/lib/python3.12/dist-packages/pytorch_tabular/tabular_datamodule.py:392: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-0.08893368  1.37408806 -0.82044456 -0.08893368  2.10559893 -1.55195543
  0.64257719 -0.08893368 -1.55195543 -0.82044456  0.64257719 -0.82044456
 -2.2834663   0.64257719 -0.08893368 -0.82044456  0.64257719 -0.82044456
 -0.08893368  0.64257719 -0.82044456  1.37408806 -0.08893368 -0.82044456
  0.64257719 -0.08893368  0.64257719 -1.55195543 -0.08893368  0.64257719
 -0.82044456  0.64257719 -0.82044456 -1.55195543  1.37408806 -0.08893368
 -0.82044456  0.64257719  1.37408806 -0.82044456 -0.08893368  0.64257719
 -0.82044456  1.37408806 -0.82044456 -0.08893368 -0.82044456 -0.82044456
  2.83710981 -0.82044456 -0.82044456 -0.08893368 -0.82044456  1.37408806
 -0.08893368  0.64257719  0.64257719 -0.82044456 -0.08893368 -0.82044456
 -1.55195543 -0.82044456  1.37408806  2.10559893  1.37408806 -0.08893368
 -0.82044456  1.37408806 -0.82044456 -0.08893368 -0.82044456 -0.82044456
 -1.55195543 -2.2834663   2.10559893 -0.08893368  1.37408806  0.64257719
 -0.82044456 -0.82044456 -0.08893368 -0.82044456 -0.82044456 -0.82044456
 -0.08893368 -1.55195543  1.37408806  0.64257719 -0.08893368  0.64257719
 -0.82044456 -0.82044456 -0.82044456  0.64257719 -1.55195543 -0.08893368
  0.64257719  0.64257719  0.64257719  0.64257719 -0.08893368  0.64257719
  0.64257719  0.64257719 -0.82044456 -0.08893368 -0.08893368  1.37408806
 -0.82044456 -0.82044456 -3.01497718 -0.82044456 -0.82044456 -0.82044456
  0.64257719 -0.82044456 -1.55195543 -1.55195543 -0.08893368  1.37408806
  0.64257719 -0.08893368 -0.08893368 -0.08893368 -0.08893368 -0.82044456
  0.64257719 -0.82044456 -0.82044456  0.64257719  0.64257719  1.37408806
  0.64257719 -0.08893368 -3.01497718  2.83710981  2.10559893 -0.82044456
  0.64257719  2.83710981  1.37408806 -0.82044456 -0.08893368 -0.08893368
 -0.82044456 -0.82044456  0.64257719  0.64257719 -0.82044456 -2.2834663
 -1.55195543 -0.08893368 -0.08893368 -0.82044456 -2.2834663  -0.82044456
 -1.55195543 -0.08893368 -1.55195543 -0.82044456  1.37408806 -0.08893368
  1.37408806 -0.82044456 -0.82044456 -0.82044456  0.64257719  1.37408806
  2.10559893  0.64257719  2.10559893 -1.55195543 -0.82044456 -0.08893368
  1.37408806 -1.55195543 -0.08893368  0.64257719 -0.82044456 -0.08893368
 -0.82044456 -0.82044456 -0.82044456  0.64257719  1.37408806  0.64257719
  1.37408806  0.64257719  0.64257719 -1.55195543 -0.82044456 -0.82044456
 -0.82044456 -0.08893368 -0.08893368 -0.82044456  1.37408806 -1.55195543
  1.37408806 -0.82044456  0.64257719  0.64257719 -0.82044456  1.37408806
  0.64257719 -0.82044456  1.37408806 -0.82044456 -0.08893368 -0.82044456
  0.64257719 -0.08893368 -1.55195543 -0.08893368  0.64257719  1.37408806
  0.64257719 -0.82044456 -0.82044456 -0.82044456 -0.82044456  1.37408806
 -0.82044456 -0.82044456  1.37408806 -0.08893368 -1.55195543 -1.55195543
 -0.08893368 -1.55195543 -1.55195543 -0.08893368 -0.08893368 -1.55195543
  1.37408806 -0.08893368  0.64257719 -0.08893368  0.64257719 -0.08893368
 -0.08893368  0.64257719  0.64257719  2.83710981 -0.08893368 -0.82044456
 -0.08893368 -0.08893368 -0.82044456 -0.82044456 -0.82044456  0.64257719
 -0.82044456 -0.82044456 -0.82044456 -0.08893368 -0.08893368 -0.82044456
 -0.08893368  1.37408806  1.37408806 -0.08893368 -0.82044456  0.64257719
  0.64257719 -0.08893368 -0.08893368 -0.08893368 -1.55195543  0.64257719
  2.83710981  1.37408806  0.64257719 -0.82044456 -1.55195543 -0.82044456
  0.64257719  2.10559893 -0.82044456 -0.82044456  0.64257719 -0.82044456
  0.64257719 -0.82044456  1.37408806 -0.08893368  0.64257719 -1.55195543
  0.64257719  0.64257719 -1.55195543 -1.55195543]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  data.loc[:, self.config.continuous_cols] = self.scaler.transform(data.loc[:, self.config.continuous_cols])
/usr/local/lib/python3.12/dist-packages/pytorch_tabular/tabular_datamodule.py:392: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ 2.16500001 -0.52417405  0.3722173   1.26860866 -0.52417405  0.3722173
  3.06139137 -0.52417405  0.3722173   1.26860866  1.26860866  0.3722173
 -1.42056541 -0.52417405 -0.52417405  1.26860866 -0.52417405  1.26860866
 -0.52417405 -0.52417405 -1.42056541 -0.52417405 -0.52417405  1.26860866
 -0.52417405 -0.52417405 -0.52417405 -0.52417405 -0.52417405 -0.52417405
  2.16500001 -0.52417405  0.3722173   1.26860866 -0.52417405  0.3722173
 -1.42056541 -0.52417405  1.26860866 -0.52417405  0.3722173  -0.52417405
 -0.52417405 -0.52417405 -0.52417405 -1.42056541 -0.52417405  1.26860866
 -0.52417405 -0.52417405  1.26860866 -0.52417405  0.3722173   0.3722173
 -0.52417405 -0.52417405 -0.52417405  0.3722173  -0.52417405  1.26860866
  0.3722173   1.26860866 -0.52417405 -0.52417405 -0.52417405  1.26860866
  0.3722173  -0.52417405 -0.52417405 -0.52417405 -0.52417405 -0.52417405
  0.3722173  -1.42056541 -0.52417405 -0.52417405 -0.52417405 -0.52417405
  0.3722173   1.26860866  2.16500001 -3.21334812 -0.52417405  2.16500001
  1.26860866  1.26860866 -0.52417405 -0.52417405 -0.52417405 -0.52417405
  0.3722173  -0.52417405  1.26860866 -0.52417405 -0.52417405 -0.52417405
  1.26860866 -0.52417405 -0.52417405  1.26860866 -2.31695677 -0.52417405
  0.3722173   2.16500001  1.26860866 -2.31695677  2.16500001 -0.52417405
 -0.52417405 -0.52417405 -2.31695677 -0.52417405  2.16500001  2.16500001
 -0.52417405  1.26860866  1.26860866 -0.52417405 -0.52417405 -0.52417405
 -0.52417405 -0.52417405 -0.52417405  1.26860866 -0.52417405  0.3722173
 -0.52417405  0.3722173   0.3722173  -0.52417405 -0.52417405 -0.52417405
 -0.52417405  0.3722173  -2.31695677 -0.52417405 -0.52417405  0.3722173
 -0.52417405  0.3722173  -0.52417405  1.26860866 -0.52417405 -0.52417405
 -0.52417405 -0.52417405  1.26860866 -0.52417405  2.16500001 -2.31695677
 -0.52417405 -0.52417405 -2.31695677 -0.52417405 -1.42056541 -0.52417405
 -1.42056541 -0.52417405  1.26860866  0.3722173  -0.52417405 -0.52417405
 -0.52417405  0.3722173  -0.52417405 -1.42056541 -0.52417405 -0.52417405
 -0.52417405  1.26860866 -0.52417405  0.3722173  -0.52417405  0.3722173
 -0.52417405 -1.42056541 -1.42056541 -0.52417405  0.3722173  -0.52417405
  2.16500001 -0.52417405 -0.52417405  2.16500001 -0.52417405  0.3722173
 -0.52417405 -0.52417405 -0.52417405 -0.52417405 -0.52417405  0.3722173
  1.26860866  0.3722173  -0.52417405  2.16500001 -0.52417405 -1.42056541
 -0.52417405  0.3722173  -0.52417405 -0.52417405  1.26860866 -0.52417405
 -0.52417405 -0.52417405 -0.52417405  0.3722173  -0.52417405 -0.52417405
 -0.52417405 -0.52417405 -0.52417405 -0.52417405  1.26860866 -0.52417405
 -0.52417405  0.3722173  -1.42056541 -0.52417405 -0.52417405 -0.52417405
  0.3722173   0.3722173  -0.52417405  1.26860866 -1.42056541  0.3722173
  2.16500001  1.26860866  1.26860866 -0.52417405  0.3722173   0.3722173
 -0.52417405  1.26860866 -0.52417405  0.3722173  -0.52417405 -0.52417405
  2.16500001  1.26860866  1.26860866 -0.52417405  0.3722173   1.26860866
 -0.52417405  0.3722173   1.26860866 -0.52417405 -0.52417405 -0.52417405
 -0.52417405  0.3722173  -0.52417405 -0.52417405  2.16500001  1.26860866
 -0.52417405 -0.52417405 -0.52417405  0.3722173   0.3722173  -0.52417405
 -0.52417405 -0.52417405 -0.52417405 -0.52417405 -0.52417405 -0.52417405
 -0.52417405 -0.52417405 -0.52417405 -2.31695677 -0.52417405  0.3722173
 -0.52417405 -0.52417405  2.16500001  0.3722173  -0.52417405  1.26860866
 -0.52417405  2.16500001 -0.52417405  1.26860866 -0.52417405  1.26860866
 -0.52417405 -0.52417405 -0.52417405  1.26860866]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  data.loc[:, self.config.continuous_cols] = self.scaler.transform(data.loc[:, self.config.continuous_cols])
/usr/local/lib/python3.12/dist-packages/pytorch_tabular/tabular_datamodule.py:392: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-2.59789311e-01  7.51222229e-01 -1.43386723e+00 -7.81601718e-01
  1.17519481e+00  3.37301685e-02 -1.04250792e+00  2.29409821e-01
 -3.14963825e-02 -5.20695514e-01 -1.40125395e+00 -9.67229334e-02
 -1.17296102e+00  1.07735498e+00  9.46901881e-01 -5.85922065e-01
  1.07735498e+00 -3.57629137e-01 -1.66216016e+00  1.04474171e+00
 -4.55468963e-01  1.20780809e+00  1.10996826e+00 -4.88082239e-01
  9.14288606e-01  7.18608953e-01  1.17519481e+00 -6.51148616e-01
  8.49062055e-01  1.14258153e+00 -2.05351946e+00  1.04474171e+00
 -8.14214994e-01 -4.88082239e-01  1.14258153e+00 -1.94562760e-01
 -6.83761892e-01  1.04474171e+00  7.18608953e-01 -4.88082239e-01
 -1.20557430e+00  7.51222229e-01  1.11689300e-03  1.20780809e+00
 -3.25015862e-01 -2.96669117e+00 -2.27176035e-01 -1.61949484e-01
  1.20780809e+00 -4.22855688e-01 -6.83761892e-01  1.96796546e-01
  1.64183270e-01  1.64183270e-01  1.07735498e+00  1.10996826e+00
  7.18608953e-01  1.96796546e-01  1.64183270e-01 -5.20695514e-01
 -1.43386723e+00 -3.90242413e-01  1.07735498e+00  1.20780809e+00
  1.14258153e+00 -6.83761892e-01 -1.00989465e+00  1.04474171e+00
  6.53382402e-01  9.14288606e-01  2.62023097e-01 -9.67229334e-02
 -4.55468963e-01 -6.83761892e-01  1.24042136e+00  8.16448780e-01
  8.49062055e-01  7.18608953e-01 -3.90242413e-01  3.37301685e-02
  3.37301685e-02 -1.66216016e+00 -5.53308790e-01 -1.07512120e+00
  2.29409821e-01 -1.17296102e+00  1.14258153e+00  4.90316025e-01
  1.07735498e+00  1.14258153e+00 -7.48988443e-01 -6.41096579e-02
  3.59862923e-01  4.90316025e-01 -9.67229334e-02  1.10996826e+00
 -1.49909378e+00  9.14288606e-01  1.14258153e+00  2.94636372e-01
 -3.14963825e-02  1.04474171e+00  6.63434439e-02 -1.36864068e+00
  2.29409821e-01 -4.55468963e-01 -6.41096579e-02  4.57702749e-01
  7.51222229e-01 -6.41096579e-02 -1.14034775e+00  2.29409821e-01
 -2.92402586e-01 -1.66216016e+00  1.14258153e+00 -1.00989465e+00
 -5.53308790e-01  1.11689300e-03  2.29409821e-01  1.04474171e+00
  8.81675330e-01  1.07735498e+00  8.49062055e-01 -1.56432033e+00
  5.55542576e-01 -1.94562760e-01  9.46901881e-01 -1.33602740e+00
  7.83835504e-01  1.64183270e-01  1.07735498e+00  1.10996826e+00
  8.81675330e-01 -1.92306636e+00 -7.16375167e-01  1.14258153e+00
  1.20780809e+00  1.31569995e-01  1.01212843e+00  7.51222229e-01
  7.83835504e-01 -4.88082239e-01  4.57702749e-01 -1.49909378e+00
 -5.20695514e-01 -1.29336209e-01 -1.14034775e+00  9.79515157e-01
  3.37301685e-02 -1.85783981e+00 -1.59693360e+00 -1.61949484e-01
 -4.55468963e-01 -3.57629137e-01 -1.59693360e+00  9.89567194e-02
 -6.41096579e-02 -5.53308790e-01 -1.66216016e+00 -3.25015862e-01
  1.17519481e+00  2.94636372e-01  1.17519481e+00 -4.55468963e-01
 -7.81601718e-01 -3.25015862e-01  8.49062055e-01  1.17519481e+00
  1.10996826e+00 -1.00989465e+00  1.04474171e+00 -4.88082239e-01

Index(['SalePrice_prediction'], dtype='object')

In [34]:
#Metrikleri hesaplarız
mae_ft = mean_absolute_error(y_true, y_pred)
rmse_ft = np.sqrt(mean_squared_error(y_true, y_pred))
r2_ft = r2_score(y_true, y_pred)

print("FT-Transformer Validation Results")
print(f"MAE  : {mae_ft:.4f}")
print(f"RMSE : {rmse_ft:.4f}")
print(f"R2   : {r2_ft:.4f}")

FT-Transformer Validation Results
MAE  : 0.3332
RMSE : 0.4317
R2   : 0.0013

In [35]:
#test tahmin ve submissionu oluşturma
test_pred_df = tabular_model.predict(X_test)
pred_col_test = "prediction" if "prediction" in test_pred_df.columns else test_pred_df.columns[-1]

test_preds_log = test_pred_df[pred_col_test].values
test_preds = np.expm1(test_preds_log)

submission = pd.DataFrame({
    "Id": test_ids,
    "SalePrice": test_preds
})

submission.to_csv("submission_ft_transformer.csv", index=False)
submission.head()

/usr/local/lib/python3.12/dist-packages/pytorch_tabular/tabular_datamodule.py:392: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-0.8667643  -0.8667643   0.07410996 ... -0.8667643   0.66215637
  0.07410996]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  data.loc[:, self.config.continuous_cols] = self.scaler.transform(data.loc[:, self.config.continuous_cols])
/usr/local/lib/python3.12/dist-packages/pytorch_tabular/tabular_datamodule.py:392: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ 0.08669258  0.33263021  0.29199704 ...  0.86569654 -0.02311926
 -0.09880669]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  data.loc[:, self.config.continuous_cols] = self.scaler.transform(data.loc[:, self.config.continuous_cols])
/usr/local/lib/python3.12/dist-packages/pytorch_tabular/tabular_datamodule.py:392: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-0.82044456 -0.08893368 -0.82044456 ... -0.82044456 -0.82044456
  0.64257719]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  data.loc[:, self.config.continuous_cols] = self.scaler.transform(data.loc[:, self.config.continuous_cols])
/usr/local/lib/python3.12/dist-packages/pytorch_tabular/tabular_datamodule.py:392: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ 0.3722173   0.3722173  -0.52417405 ...  1.26860866 -0.52417405
 -0.52417405]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  data.loc[:, self.config.continuous_cols] = self.scaler.transform(data.loc[:, self.config.continuous_cols])
/usr/local/lib/python3.12/dist-packages/pytorch_tabular/tabular_datamodule.py:392: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-0.32501586 -0.42285569  0.84906205 ... -0.35762914  0.68599568
  0.71860895]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  data.loc[:, self.config.continuous_cols] = self.scaler.transform(data.loc[:, self.config.continuous_cols])
/usr/local/lib/python3.12/dist-packages/pytorch_tabular/tabular_datamodule.py:392: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-1.15306013 -1.2978123   0.63221669 ...  0.53571524  0.34271234
  0.43921379]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  data.loc[:, self.config.continuous_cols] = self.scaler.transform(data.loc[:, self.config.continuous_cols])
/usr/local/lib/python3.12/dist-packages/pytorch_tabular/tabular_datamodule.py:392: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-0.68742066 -0.68742066 -0.68742066 ... -0.68742066 -0.68742066
 -0.68742066]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  data.loc[:, self.config.continuous_cols] = self.scaler.transform(data.loc[:, self.config.continuous_cols])
/usr/local/lib/python3.12/dist-packages/pytorch_tabular/tabular_datamodule.py:392: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-0.24121363 -0.24121363 -0.24121363 ... -0.24121363 -0.24121363
 -0.24121363]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  data.loc[:, self.config.continuous_cols] = self.scaler.transform(data.loc[:, self.config.continuous_cols])
/usr/local/lib/python3.12/dist-packages/pytorch_tabular/tabular_datamodule.py:392: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-0.56620052 -0.56620052  0.58592876 ... -0.56620052  0.58592876
  0.58592876]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  data.loc[:, self.config.continuous_cols] = self.scaler.transform(data.loc[:, self.config.continuous_cols])
/usr/local/lib/python3.12/dist-packages/pytorch_tabular/tabular_datamodule.py:392: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[0.11014407 0.11014407 0.11014407 ... 0.11014407 0.11014407 0.11014407]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  data.loc[:, self.config.continuous_cols] = self.scaler.transform(data.loc[:, self.config.continuous_cols])
/usr/local/lib/python3.12/dist-packages/pytorch_tabular/tabular_datamodule.py:392: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-1.16829211 -1.16829211 -0.1321758  ...  0.90394052 -1.16829211
  0.90394052]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  data.loc[:, self.config.continuous_cols] = self.scaler.transform(data.loc[:, self.config.continuous_cols])
/usr/local/lib/python3.12/dist-packages/pytorch_tabular/tabular_datamodule.py:392: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-0.70723826  0.41304409 -0.62444604 ...  0.14138209 -0.51578123
 -0.44851255]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  data.loc[:, self.config.continuous_cols] = self.scaler.transform(data.loc[:, self.config.continuous_cols])
/usr/local/lib/python3.12/dist-packages/pytorch_tabular/tabular_datamodule.py:392: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-0.80192292 -0.80192292  0.79349734 ... -0.80192292 -0.80192292
  1.48310125]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  data.loc[:, self.config.continuous_cols] = self.scaler.transform(data.loc[:, self.config.continuous_cols])
/usr/local/lib/python3.12/dist-packages/pytorch_tabular/tabular_datamodule.py:392: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-0.11899866 -0.11899866 -0.11899866 ... -0.11899866 -0.11899866
 -0.11899866]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  data.loc[:, self.config.continuous_cols] = self.scaler.transform(data.loc[:, self.config.continuous_cols])
/usr/local/lib/python3.12/dist-packages/pytorch_tabular/tabular_datamodule.py:392: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-1.20448634 -0.37847856  0.1938132  ... -0.57878068 -1.06332104
  0.90154735]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  data.loc[:, self.config.continuous_cols] = self.scaler.transform(data.loc[:, self.config.continuous_cols])
/usr/local/lib/python3.12/dist-packages/pytorch_tabular/tabular_datamodule.py:392: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-1.05556573 -1.05556573  0.7736639  ... -1.05556573 -1.05556573
  0.7736639 ]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  data.loc[:, self.config.continuous_cols] = self.scaler.transform(data.loc[:, self.config.continuous_cols])
/usr/local/lib/python3.12/dist-packages/pytorch_tabular/tabular_datamodule.py:392: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-0.76409752  1.23694711  1.23694711 ... -0.76409752 -0.76409752
  1.23694711]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  data.loc[:, self.config.continuous_cols] = self.scaler.transform(data.loc[:, self.config.continuous_cols])
/usr/local/lib/python3.12/dist-packages/pytorch_tabular/tabular_datamodule.py:392: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-1.10677385  0.13621832  0.13621832 ...  1.37921049  0.13621832
  0.13621832]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  data.loc[:, self.config.continuous_cols] = self.scaler.transform(data.loc[:, self.config.continuous_cols])
/usr/local/lib/python3.12/dist-packages/pytorch_tabular/tabular_datamodule.py:392: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-0.21275711 -0.21275711 -0.21275711 ... -0.21275711 -0.21275711
 -0.21275711]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  data.loc[:, self.config.continuous_cols] = self.scaler.transform(data.loc[:, self.config.continuous_cols])
/usr/local/lib/python3.12/dist-packages/pytorch_tabular/tabular_datamodule.py:392: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-0.76707624  0.74634445 -0.76707624 ... -0.76707624 -0.76707624
 -0.76707624]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  data.loc[:, self.config.continuous_cols] = self.scaler.transform(data.loc[:, self.config.continuous_cols])
/usr/local/lib/python3.12/dist-packages/pytorch_tabular/tabular_datamodule.py:392: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-0.96456591 -0.34690528 -0.34690528 ...  0.27075534 -0.34690528
  1.50607659]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  data.loc[:, self.config.continuous_cols] = self.scaler.transform(data.loc[:, self.config.continuous_cols])
/usr/local/lib/python3.12/dist-packages/pytorch_tabular/tabular_datamodule.py:392: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-0.95859215 -0.95859215  0.59214972 ...  0.59214972 -0.95859215
  0.59214972]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  data.loc[:, self.config.continuous_cols] = self.scaler.transform(data.loc[:, self.config.continuous_cols])
/usr/local/lib/python3.12/dist-packages/pytorch_tabular/tabular_datamodule.py:392: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-1.0162412  -1.0162412   0.63922564 ...  0.63922564 -1.0162412
  0.63922564]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  data.loc[:, self.config.continuous_cols] = self.scaler.transform(data.loc[:, self.config.continuous_cols])
/usr/local/lib/python3.12/dist-packages/pytorch_tabular/tabular_datamodule.py:392: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ 0.25314289  0.25314289  0.25314289 ...  0.25314289 -3.91123593
  0.25314289]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  data.loc[:, self.config.continuous_cols] = self.scaler.transform(data.loc[:, self.config.continuous_cols])
/usr/local/lib/python3.12/dist-packages/pytorch_tabular/tabular_datamodule.py:392: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ 0.2580102   0.2580102   0.2580102  ...  0.2580102  -3.92748859
  0.2580102 ]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  data.loc[:, self.config.continuous_cols] = self.scaler.transform(data.loc[:, self.config.continuous_cols])
/usr/local/lib/python3.12/dist-packages/pytorch_tabular/tabular_datamodule.py:392: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ 0.33983601  2.29153854  0.89526124 ...  2.91639192 -0.12301834
  0.72554798]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  data.loc[:, self.config.continuous_cols] = self.scaler.transform(data.loc[:, self.config.continuous_cols])
/usr/local/lib/python3.12/dist-packages/pytorch_tabular/tabular_datamodule.py:392: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-0.71435182 -0.19564861 -0.22446546 ... -0.71435182 -0.2532823
 -0.02274754]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  data.loc[:, self.config.continuous_cols] = self.scaler.transform(data.loc[:, self.config.continuous_cols])
/usr/local/lib/python3.12/dist-packages/pytorch_tabular/tabular_datamodule.py:392: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-0.35192107 -0.35192107 -0.35192107 ... -0.35192107 -0.35192107
 -0.35192107]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  data.loc[:, self.config.continuous_cols] = self.scaler.transform(data.loc[:, self.config.continuous_cols])
/usr/local/lib/python3.12/dist-packages/pytorch_tabular/tabular_datamodule.py:392: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-0.12100805 -0.12100805 -0.12100805 ... -0.12100805 -0.12100805
 -0.12100805]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  data.loc[:, self.config.continuous_cols] = self.scaler.transform(data.loc[:, self.config.continuous_cols])
/usr/local/lib/python3.12/dist-packages/pytorch_tabular/tabular_datamodule.py:392: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ 1.87249677 -0.27583782 -0.27583782 ... -0.27583782 -0.27583782
 -0.27583782]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  data.loc[:, self.config.continuous_cols] = self.scaler.transform(data.loc[:, self.config.continuous_cols])
/usr/local/lib/python3.12/dist-packages/pytorch_tabular/tabular_datamodule.py:392: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-0.07099284 -0.07099284 -0.07099284 ... -0.07099284 -0.07099284
 -0.07099284]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  data.loc[:, self.config.continuous_cols] = self.scaler.transform(data.loc[:, self.config.continuous_cols])
/usr/local/lib/python3.12/dist-packages/pytorch_tabular/tabular_datamodule.py:392: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-0.06801146 -0.06801146 -0.06801146 ... -0.06801146 -0.06801146
 -0.06801146]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  data.loc[:, self.config.continuous_cols] = self.scaler.transform(data.loc[:, self.config.continuous_cols])
/usr/local/lib/python3.12/dist-packages/pytorch_tabular/tabular_datamodule.py:392: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-0.09274033 22.51929789 -0.09274033 ... -0.09274033  1.17353381
 -0.09274033]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  data.loc[:, self.config.continuous_cols] = self.scaler.transform(data.loc[:, self.config.continuous_cols])
/usr/local/lib/python3.12/dist-packages/pytorch_tabular/tabular_datamodule.py:392: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-0.13341669 -0.13341669 -1.25719573 ...  0.99036235  0.24117632
  1.73954838]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  data.loc[:, self.config.continuous_cols] = self.scaler.transform(data.loc[:, self.config.continuous_cols])
/usr/local/lib/python3.12/dist-packages/pytorch_tabular/tabular_datamodule.py:392: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ 1.65006527  1.65006527  1.65006527 ... -1.37548612 -1.37548612
 -1.37548612]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  data.loc[:, self.config.continuous_cols] = self.scaler.transform(data.loc[:, self.config.continuous_cols])
/usr/local/lib/python3.12/dist-packages/pytorch_tabular/tabular_datamodule.py:392: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ 0.32501586  0.42285569 -0.84906205 ...  0.35762914 -0.68599568
 -0.71860895]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  data.loc[:, self.config.continuous_cols] = self.scaler.transform(data.loc[:, self.config.continuous_cols])
/usr/local/lib/python3.12/dist-packages/pytorch_tabular/tabular_datamodule.py:392: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ 1.15306013  1.2978123  -0.63221669 ... -0.53571524 -0.34271234
 -0.43921379]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  data.loc[:, self.config.continuous_cols] = self.scaler.transform(data.loc[:, self.config.continuous_cols])
/usr/local/lib/python3.12/dist-packages/pytorch_tabular/tabular_datamodule.py:392: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ 0.27160794 -0.50541489 -0.52391544 ... -0.83842468 -0.54241598
 -0.39441163]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  data.loc[:, self.config.continuous_cols] = self.scaler.transform(data.loc[:, self.config.continuous_cols])

     Id      SalePrice
0  1461  162771.953125
1  1462  162567.796875
2  1463  162816.359375
3  1464  162810.140625
4  1465  162767.609375